### ISSUE TITLE
Plan

### ISSUE THREAD

**Issue by dhardy** [rust-random/getrandom#1]
To get this going:

- [x] create repository
- [x] publish initial crate
- [x] set up CI (services are now enabled, but not yet configured)
- [x] copy over initial code from `OsRng`
- [x] implement for WASM
- [x] document #7
- [x] review error type #3 
- [x] publish this as 0.1

**Comment by dhardy** [comment]
@newpavlov would you like to take the next step here? I think the logical approach would be to make the initial version dependent on `rand_core` and try migrating away from that afterwards.

**Comment by newpavlov** [comment]
I think we can go with a stripped down version right away. I will try to prepare a PR.

**Comment by newpavlov** [comment]
Don't forget about implementing WASM targets.

**Comment by dhardy** [comment]
We seem to have settled on an error type, though #3 can stay open for now (we may add `is_retryable` later). Thus I think we are ready for a 0.1 release, once you've prepared your suggested changes.
