### ISSUE TITLE
Missing `std::error::Error` for `genrandom::error::Error` on Windows?

### ISSUE THREAD

**Issue by vi** [rust-random/getrandom#132]
the trait `std::error::Error` is not implemented for `getrandom::error::Error`

Why error being a normal error is platform-dependent?

**Comment by newpavlov** [comment]
Because `getrandom` is a `no_std` crate by default. `std::error::Error` [implementation](https://github.com/rust-random/getrandom/blob/master/src/error_impls.rs) is feature-gated behind `std` feature, so you just need to enable it.

**Comment by vi** [comment]
Why it gets auto-enabled on Linux?

**Comment by newpavlov** [comment]
Because it was an oversight which we have to keep for backward compatibility, but we plan to remove it in v0.2 (see #98).

**Comment by josephlr** [comment]
Closing this as this was fixed in 0.2 for #106. General 0.2 progress is tracked in #98
