### ISSUE TITLE
Comment on WASM targets where getrandom should never work

### ISSUE THREAD

**Issue by vks** [rust-random/getrandom#152]
@burdges in https://github.com/rust-random/rand/issues/991:

> There exist wasm targets where getrandom should never work, which may warrant a comment somewhere.

**Comment by burdges** [comment]
I donno much about the range of wasm targets that exist, or what normally happens, but wasm was meant to be quite deterministic, and ours bans any form of randomness or secrets.

**Comment by josephlr** [comment]
This will get clarified w/ the `0.2` release (see #135). But the basic idea is:
  - `getrandom` works perfectly fine on `wasm32-unknown-emscripten` and `wasm32-wasi`
  - `getrandom` does not automatically work on `wasm32-unknown-unknown`
    - Enabling the `getrandom/js` cargo feature will make this target work
    - Enabling this feature essentially says "I assume I'm running in an enviornment w/ JavaScript". This includes:
      - [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) or [stdweb](https://github.com/koute/stdweb) toolchains
      - Client-side (in Browser) or Node.js
  - There are no other Rust `wasm32` targets that I am aware of. If new ones are added, they would not automatically work, and a pull request to getrandom would be needed.

Comment either here or in the doc bug if the above seems unclear or incorrect.

**Comment by burdges** [comment]
I believe the rust target is wasm32-unknown-unknown.  If I read lib.rs correctly, wasm32-unknown-unknown without wasm32_bindgen or wasm32_stdweb compiles to dummy.rs, which always errors.  This is correct behavior for "perfectly" deterministic wasm targets.  I think this can be closed.

**Comment by josephlr** [comment]
Sounds good.

> If I read lib.rs correctly, wasm32-unknown-unknown without wasm32_bindgen or wasm32_stdweb compiles to dummy.rs, which always errors. This is correct behavior for "perfectly" deterministic wasm targets. I think this can be closed.

This is correct for 0.1, for 0.2 we are changing things so that `getrandom` will not compile on unsupported targets (i.e. `wasm32-unknown-unknown` without JavaScript). See [`lib.rs` on the `0.2` branch](https://github.com/rust-random/getrandom/blob/0.2/src/lib.rs)

**Comment by burdges** [comment]
I see, getrandom is already an optional dependency of rand_core and rand though, so this sounds good too.

**Comment by Spoonbender** [comment]
It would actually be nice to be able to use rand's `getrandom` feature in a `wasm32-unknown-unknown` environment with JS. How about adding a "JS" feature to rand, which will enable the JS feature of getrandom?
