### ISSUE TITLE
A way to avoid wasm-bindgen dependency?

### ISSUE THREAD

**Issue by RazrFalcon** [rust-random/getrandom#176]
Currently, a vendored `getrandom` archive includes 40! dependencies and 20MB on disk. This is not a problem when people simply using it as a crate, because all of those dependencies will be omitted, but in case of a vendored archive use case it ends up as pretty serious bloat.

Is there a way to reduces the number of indirect dependencies?

**Comment by newpavlov** [comment]
Optional dependencies by default do not get vendored-in. In a new crate dependent only on `getrandom` I get 4 crates in the `vendor` folder: `cfg-if`, `getrandom`, `libc`, and `wasi`.

**Comment by RazrFalcon** [comment]
Ok. My mistake. Then we left with `wasm-bindgen` which has like 10 dependencies.

**Comment by RazrFalcon** [comment]
Wait, so is there a way to remove `wasm-bindgen`?

**Comment by newpavlov** [comment]
Yes, if the crate feature which does not enable `wasm-bindgen` is not enabled, then it and all its dependencies should not get vendored (I assume you use `cargo vendor`). Probably one of your dependencies unconditionally enables this feature (e.g. via `rand` which in v0.7 forwards the `wasm-bindgen` feature), so you need to find it and ask for a fix.

**Comment by RazrFalcon** [comment]
To be more precise, I'm building the `uuid` crate with `wasm-bindgen` feature, to make it work in web. Which pulls `wasm-bindgen`. Maybe there is a way to avoid it altogether?

**Comment by newpavlov** [comment]
If you don't need UUIDv4 (random UUIDS), simply do not enable `wasm-bindgen` and `v4` features. If you need randomness from browser, then `wasm-bindgen` is a required dependency. Without it you will not be able to talk with browser environment while using the `wasm32-unknown-unknown` target.

**Comment by RazrFalcon** [comment]
>then wasm-bindgen is a required dependency.

I see. This is what I wanted to hear. Thanks.
