### ISSUE TITLE
Add CI for WASM targets

### ISSUE THREAD

**Issue by newpavlov** [rust-random/getrandom#181]
In #180 we have migrated to GitHub Actions almost all tests except related to WASM and Emscripten.

[Old Travis config](https://github.com/rust-random/getrandom/blob/2d899940a2a4968f81b3e715deef1a6d47cf5801/.travis.yml#L37-L97)

**Comment by josephlr** [comment]
With the stdweb support removed in #178, this should now be easier to get working. The best approach might be to have a Dockerfile containing the Node/Firefox/Chromium deps, so that we can keep all of those ordered in a single place.
