### ISSUE TITLE
New tagged release for crates.io using cfg-if = "1"

### ISSUE THREAD

**Issue by Dragonrun1** [rust-random/getrandom#186]
So the master has been switch to using cfg-if v1 but the getrandom v0.2.0 on crates.io is still on the older version. Now that rand v0.8.0 has been released using cfg-if v1 it would be nice to have a published version of getrandom that has done the same.

**Comment by newpavlov** [comment]
@josephlr 
Would you like to cut a release before merging the pending PRs? I would prefer to merge the PRs first and release v0.2.1 with all accumulated changes.

**Comment by josephlr** [comment]
@newpavlov I'll should be able to get to these tomorrow, after I merge I'll cut 0.2.1

**Comment by josephlr** [comment]
`getrandom v0.2.1` has been published https://crates.io/crates/getrandom/0.2.1

Now that this and `v0.1.16` have been released, this issue can be closed.
