### ISSUE TITLE
RDRAND backend

### ISSUE THREAD

**Issue by dhardy** [rust-random/getrandom#2]
Discussed in https://github.com/rust-random/rand/issues/699, we may use RDRAND as a fallback generator. This is already used by `OsRng` for SGX where no other generators are available.

We could depend on the [rdrand](https://crates.io/crates/rdrand) crate, but my preference is to avoid dependence on `rand_core`, which implies we would need another implementation (probably just as an internal module).

License note: the rdrand code uses the [ISC licence](https://github.com/nagisa/rust_rdrand/blob/master/LICENSE); I think this means we can simply relicence this under MIT+APLv2, though we should of course mention @nagisa's copyright. (Also note: the MIT license [arguably includes a patent grant](https://opensource.com/article/18/3/patent-grant-mit-license) anyway; probably the ISC licence is equivalent.)

**Comment by newpavlov** [comment]
For SGX target I think we can use rdrand intrinsic directly, as code is quite simple. But there is a question about whether we should use RDRAND or RDSEED here. Here is a [blog post](https://software.intel.com/en-us/blogs/2012/11/17/the-difference-between-rdrand-and-rdseed) from Intel regarding the difference between them. Even though `getrandom` will be often used for seeding I think we should still stick with the RDRAND.

**Comment by dhardy** [comment]
The the linked blog, it sounds (vaguely) similar to the `/dev/random` and `/dev/urandom` distinction on Linux. In theory we could have two "grades" of quality, but it sounds completely unnecessary (from what I understand, *most* people recommend using `/dev/urandom` in all cases, aside from early boot (not applicable here) and [information-theoretical security](https://crypto.stackexchange.com/questions/35031/if-i-am-about-to-generate-one-time-pad-where-should-i-generate-my-pads-from)).

**Comment by newpavlov** [comment]
From [here](https://github.com/rust-random/getrandom/issues/3#issuecomment-464826485):

>I still plan to discuss using RDRAND as a backup option.

Personally I am strongly against it. As I've wrote earlier I believe that we should keep `getrandom` as thin as possible, especially considering potential inclusion into `std`. Plus making it overwritable in future will allow users to use any fallback strategy they would like.

**Comment by tarcieri** [comment]
I would personally prefer this crate be kept as simple as possible with no built-in fallbacks. I think fallbacks should be pushed up a level into crates like `rand_os`.

If I do wind up using this crate directly directly in lieu of `rand_os`, I can manage RDRAND fallback on my own.

**Comment by dhardy** [comment]
This paper is worth a view on the topic on RDRAND and RDSEED security: [Shrimpton T., Terashima R.S. (2015) A Provable-Security Analysis of Intel’s Secure Key RNG](https://eprint.iacr.org/2014/504).

At this point we already have a minimal RDRAND [implementation for SGX](https://github.com/rust-random/getrandom/blob/master/src/sgx.rs). Interestingly, [@jethrogb disagrees that SGX implies RDRAND](https://github.com/nagisa/rust_rdrand/issues/9).

@newpavlov mentions that this lib should be a very thin wrapper, however we already have some level of abstraction: probing for `getrandom` sys-call support on Linux and Solaris, otherwise using the old interface. There is little difference there.

In terms of extra code, the addition would not be very heavy. [@nagisa's lib](https://github.com/nagisa/rust_rdrand/blob/master/src/lib.rs) is 472 lines, including a *lot* of doc and support for `next_u*` functions plus RDSEED which we don't need. Run-time overhead would be negligible, compile-time and code-size overhead low.

In terms of trust, one must already have some trust in the CPU, and as @tarcieri has noted this only has any implication on certain three-letter-agencies, who are often sensibly excluded from threat models.

This is something applicable to many users and a small addition. I have nothing against making it a separate function (e.g. `getrandom_with_fallback`), but think it would be a very nice thing to include?

**Comment by tarcieri** [comment]
> Interestingly, [@jethrogb disagrees that SGX implies RDRAND](https://github.com/nagisa/rust_rdrand/issues/9).

It's true. RDRAND won't necessarily be available, and the Intel SDK tests for it at runtime. If it's not available though, there aren't other practical options to fall back to.

**Comment by newpavlov** [comment]
>we already have some level of abstraction: probing for `getrandom` sys-call support on Linux and Solaris, otherwise using the old interface. There is little difference there.

And as you can judge by #5 I dislike it. Depending on OS support policy I hope we will be able to remove it on inclusion into `std`.

I _guess_ I wouldn't mind including RDRAND fallback for `x86` Windows targets, and only if it will be confirmed that the problem which originally caused the introduction of fallback is still present on supported Windows versions (meaning excluding XP). But I don't see any sensible reasons for adding such arch-specific fallback for all targets.

**Comment by dhardy** [comment]
Regarding the need for a feedback: see [here](https://github.com/rust-lang/rust/issues/44911#issuecomment-333182121) (and also the last post, where it is suggested this is no longer a significant issue).

**Comment by newpavlov** [comment]
>So you don't think we should support Linux older than 3.17 (and I don't know what Solaris version)?

In near-mid term future for `getrandom` crate I think we should use the version will fallback. But when (and if) we will get a language-level support for `getrandom`, I believe we should consider the minimum supported Linux kernel version which will be supported by Rust out-of-box. It's part of a broader discussion, as I believe there were some issues with non-compatible OS versions (Fedora IIRC) for which we don't have any way to differentiate at compile time. Also if I am not mistaken Rust explicitly has dropped support for Windows XP.

With Solaris there are two issues:
- Syscall was introduced in 11.3 while Solaris 10 will be supported until 2021 (and Solaris 11 will be supported until 2034)
- There are OpenSolaris [derivatives](https://en.wikipedia.org/wiki/OpenSolaris#Derivatives) which may not have syscalls and again we don't have any way to differentiate between them at compile time.

So again until we will get an ability to overwrite `getrandom` by applciations, I think we should keep the current code.

**Comment by dhardy** [comment]
I think this issue is concluded: we won't implement fall-back sources in this lib.
