### ISSUE TITLE
Thread Rng Panicking

### ISSUE THREAD

**Issue by eribol** [rust-random/getrandom#203]
I am using same code for my local pc and server. They are using same targets. At the first place, it was not panicking for thread_rng but now, my server codes gives error;
"panicked at 'could not initialize thread_rng: getrandom: this target is not supported'"

**Comment by newpavlov** [comment]
Please provide more information about your setup, at the very least yout target triplet and exact `getrandom` version. Have you tried to use `getrandom` directly?

**Comment by josephlr** [comment]
@eribol are you using `wasm32-unknown-unknown`? That would explain the error you're getting.

**Comment by eribol** [comment]
Yes, i am using wasm32-unknown-unknown. I dont know why it happened because i did not even define getrandom on my Cargo.toml. 

Anyway, now i used rand 0.8 and getrandom 0.2 and added feature = "js" and it worked well.

Sorry, it was a confusing problem for me.
