### ISSUE TITLE
feature = "rdrand" vs target_os = "linux"

### ISSUE THREAD

**Issue by jcape** [rust-random/getrandom#225]
Hi, thanks for the work on this crate, it's greatly appreciated.

I'm currently working with an SGX enclave that is not built using the Fortanix tier2 target. We're building `no_std` as `x86_64-unknown-linux-gnu`, and using nightly features to use a custom allocator. The `CHANGELOG.md` file in this repo makes it seem like our use case would be covered by recent changes with the `"rdrand"` feature, but this does not appear to be the case in the code. In particular, the `target_os = "linux"` test at https://github.com/rust-random/getrandom/blob/30308ae845b0bf3839e5a92120559eaf56048c28/src/lib.rs#L175 would be hit before the `feature = "rdrand"` https://github.com/rust-random/getrandom/blob/30308ae845b0bf3839e5a92120559eaf56048c28/src/lib.rs#L210

Is this the intended behavior?

**Comment by josephlr** [comment]
@jcape Yes, this is the intended behavior. From the ["unsupported targets" section of our documentation](https://docs.rs/getrandom/0.2.3/getrandom/#unsupported-targets):

> All of the below mechanisms only affect unsupported targets. Supported targets will always use their supported implementations. This prevents a crate from overriding a secure source of randomness (either accidentally or intentionally).

If you think the docs should have more info about this stuff, let use know and we can update them.

Basically, if you're not building for Linux (as in your case), we don't recommend using a target with `target_os = "linux"`. For your SGX taget, you should either:
  - Be using the existing Fortanix target: `x86_64-fortanix-unknown-sgx`
  - Use a custom target with (`target_env = "sgx"`), in which case this crate will automatically use `"rdrand"`.
    - See the [docs on custom targets](https://docs.rust-embedded.org/embedonomicon/custom-target.html),

**Comment by jcape** [comment]
Blech, OK. Reasonable answer, just not the one I was hoping for, thanks. ;-)
