### ISSUE TITLE
Towards rand 1.0

### ISSUE THREAD

**Issue by dhardy** [rust-random/getrandom#232]
We've had [questions](https://github.com/rust-random/rand/issues/693) about when Rand will reach 1.0. We're not there yet, but it is still worth discussing the dependency on `getrandom`.

From memory & quick skim the only part of the API which is affected by `getrandom` is `rand_core::Error`, and only in two ways:

- The declared constants [must match those in `getrandom::Error`](https://github.com/rust-random/rand/blob/master/rand_core/src/error.rs#L225). This doesn't really require `getrandom` to be 1.0 so long as there is a stability promise affecting these.
- [`impl From<getrandom::Error> for Error`](https://github.com/rust-random/rand/blob/master/rand_core/src/error.rs#L169), which thus pins `rand_core` to a single `getrandom` major-minor version.

Potential solutions:

1. Stabilise `getrandom` 1.0 soon? Seems unlikely?
2. A separate crate just for `Error` — perhaps viable but definitely not desirable
3. Use the promise above and deprecate that `impl`, forcing users to rely on [`getrandom::Error::code() -> NonZeroU32`](https://github.com/rust-random/getrandom/blob/master/src/error.rs#L87) and [`impl From<NonZeroU32> for Error`](https://github.com/rust-random/rand/blob/master/rand_core/src/error.rs#L152)

CC @vks @newpavlov

**Comment by vks** [comment]
I think the most important part of our API affected by `getrandom` is actually `SeedableRng::from_entropy`.

Why is stabilizing `getrandom` 1.0 unlikely?

**Comment by gilescope** [comment]
Great work that's being done pushing this all forward. Mouse's review seemed very positive. Let me know if I can help in any way.

**Comment by newpavlov** [comment]
As proposed [here](https://github.com/rust-random/getrandom/pull/485#discussion_r1645180720), another potential API change for 1.0 is to use [`BorrowedBuf`](https://doc.rust-lang.org/std/io/struct.BorrowedBuf.html) instead of `&mut [MaybeUninit<u8>]` for `getrandom_uninit`.

**Comment by briansmith** [comment]
> As proposed https://github.com/rust-random/getrandom/pull/485#discussion_r1645180720, another potential API change for 1.0 is to use [BorrowedBuf](https://doc.rust-lang.org/std/io/struct.BorrowedBuf.html) instead of &mut [MaybeUninit<u8>] for getrandom_uninit.

I don't know if it would make sense to change the *public* API to use BorrowedBuf/Cursor. I was suggesting there it might make sense to change the internal ones like `sys_fill_exact`. Even then I'm not sure.

**Comment by newpavlov** [comment]
I think we can close this issue for now since most of the discussion is no longer relevant.

Before considering v1.0 we need to get some experience with `getrandom` v0.3. There is also a possibility of `std` introducing a `getrandom`-like API (see https://github.com/rust-lang/rust/issues/130703) which would make this crate obsolete.

When it will be the time for rand v1.0 release we can open a new issue to consider whether we should release getrandom v1.0 or not.
