### ISSUE TITLE
target is not supported ( cargo build-bpf )

### ISSUE THREAD

**Issue by ieow** [rust-random/getrandom#237]
I am hitting this error when try to run `cargo build-bpf`  in apple M1
It works find when I run with `cargo build` in apple M1
```
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/lib.rs:224:9
    |
224 | /         compile_error!("target is not supported, for more information see: \
225 | |                         https://docs.rs/getrandom/#unsupported-targets");
    | |_________________________________________________________________________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> /Users/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/lib.rs:246:5
    |
246 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`
  
   
```
Is this behaviour expected?

**Comment by josephlr** [comment]
Yes it is. Did the linked docs page help explain things?

**Comment by ieow** [comment]
Yea, it would be great if there is small mention that cargo build-bpf is not supported.
I thought it was M1 issue.

**Comment by josephlr** [comment]
Do you know what target cargo build-bpf is using?

**Comment by ieow** [comment]
I am not really sure.
but the it create target/bpfel-unknown-unknown directory

**Comment by newpavlov** [comment]
List of unsupported targets is quite big, so I don't think we should list every such target in the docs.

**Comment by ieow** [comment]
make sense. Noted.

**Comment by johnvsnagendra** [comment]
Is there any workaround for running `cargo build-bpf` in Mac M1? 
I am still facing this issue in mac and did not find any solution. Any suggestions will be helpful. 
Thanks

**Comment by tpompon** [comment]
> Is there any workaround for running `cargo build-bpf` in Mac M1? I am still facing this issue in mac and did not find any solution. Any suggestions will be helpful. Thanks

I have the same issue :(

**Comment by josephlr** [comment]
@johnvsnagendra @tpompon is there something confusing about the docs here? You will notice the error message links to https://docs.rs/getrandom/#unsupported-targets which explains how you can provide a fallback implementation. However, given that this affects multiple people, it might be best to open an issue with [Solana](https://github.com/solana-labs/solana).

I don't think it would be possible for us to directly support the `bpfel-unknown-none` and `bpfeb-unknown-none` targets, as they don't have a built-in way to generate random data.

**Comment by josephlr** [comment]
Specifically, I think https://github.com/solana-labs/solana/issues/22810 would be a better place to discuss this.

**Comment by josephlr** [comment]
It actually seems like this is fully explained in the [Solana docs](https://github.com/solana-labs/solana/blob/master/docs/src/developing/on-chain-programs/developing-rust.md#depending-on-rand), so I don't think any work is needed here.

**Comment by tpompon** [comment]
> It actually seems like this is fully explained in the [Solana docs](https://github.com/solana-labs/solana/blob/master/docs/src/developing/on-chain-programs/developing-rust.md#depending-on-rand), so I don't think any work is needed here.

Right thank you very much for this, it's exactly what I was searching for!
