### ISSUE TITLE
Fix CI Tests

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#249]
One of the test fixes is simple just change [this line](https://github.com/rust-random/getrandom/blob/cf02327ac9d93ef46435c86214abd708c540f7d8/.github/workflows/tests.yml#L232) to `select(.name | contains("x86_64-linux"))`

I'm not sure about the solaris issue.

**Comment by newpavlov** [comment]
After re-running CI only the Solaris job now fails.

**Comment by newpavlov** [comment]
I will close this issue in favor of #254.
