### ISSUE TITLE
Prop:Question: How generate range (0..1000)

### ISSUE THREAD

**Issue by remotejob** [rust-random/getrandom#258]
Question:
Is it possible to generate a range of Integers for example (0..1000)?

As in:
use rand::Rng;
println!("Integer: {}", rng.gen_range(0..10));

**Comment by newpavlov** [comment]
No, it's outside of `getrandom` goals. You can implement the range sampling yourself (it would be a relatively simple code), but I recommend to simply use `rand`.

**Comment by remotejob** [comment]
Artyom I can't use rand. I appreciate it if you give me some startup/hint on how I can do it. 
Task: create 10 uniq int from range (1..5000). Thanks.

**Comment by josephlr** [comment]
I would look at the code for `rand` (if you really can't just use that library) see [here](https://github.com/rust-random/rand/blob/dbbc1bf3176138c867f3d84c0c4d288119a5a84e/src/distributions/uniform.rs#L518-L554). However, I would again recommend just using `rand`.

**Comment by remotejob** [comment]
Ok Thnaks.
