### ISSUE TITLE
Weak Bindings Violate Strict Provenance in MIRI

### ISSUE THREAD

**Issue by nvzqz** [rust-random/getrandom#262]
Because the [`Weak` struct](https://github.com/rust-random/getrandom/blob/v0.2.6/src/util_libc.rs#L77-L84) is defined as having `LazyUsize` for the address, it does not maintain pointer provenance and thus fails when run under MIRI with `-Zmiri-strict-provenance`.

The solution would be to define a `LazyPtr` type that utilizes `AtomicPtr` instead of `AtomicUsize`.

**Comment by josephlr** [comment]
@nvzqz I notice that the `AtomicPtr` types basically wrap a `*mut T` while we usually have something of type `unsafe extern "C" fn(*mut u8, libc::size_t, libc::c_uint) -> libc::c_int`. I know that we can cast function pointers to/from `*const ()`, but will that work with `-Zmiri-strict-provenance`?

**Comment by nvzqz** [comment]
Yes, function pointers are tracked under strict provenance. The issue is that integers lose pointer provenance information.

**Comment by josephlr** [comment]
Awesome, I'll take a look!

**Comment by josephlr** [comment]
Would you also need a 0.1 backport?

**Comment by nvzqz** [comment]
I myself do not need this fixed in 0.1. This came up due to using `rand`, which I assume most people who hit this will also be.

**Comment by josephlr** [comment]
It looks like we will have to use `1 as *mut c_void` in our code for stuff to properly compile on 1.34. Will that work with Strict Provenance provided that we never deference the invalid pointer?

**Comment by nvzqz** [comment]
My understanding is that's totally fine. Considering that [`sptr::invalid`](https://docs.rs/sptr/latest/sptr/fn.invalid.html) does exactly this, I don't see an issue.
