### ISSUE TITLE
Runtime crash in wasm32-unknown-unknown, even with "js" feature enabled.

### ISSUE THREAD

**Issue by vdods** [rust-random/getrandom#268]
This is similar to https://github.com/rust-random/getrandom/issues/208 except that it happens at runtime.

I'm building via `wasm-pack build --debug --target web`, and the build succeeds, but the following happens at runtime, when running in the browser (Firefox, if that's useful information).
```
panicked at 'Error: getrandom: this target is not supported', /home/vdods/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.5.1/src/os.rs:63:13
...
<JS stack trace omitted>
```

The output of `cargo tree --target wasm32-unknown-unknown -e features` shows that indeed the "js" feature of `getrandom` is enabled.

The error happens due to a call from the `getrandom` function, inside the `rand_core` crate.  Any idea what the problem could be?

Might it be that there's some other feature enabled within some indirect dependency that causes getrandom to attempt to use the code from a different platform?

**Comment by josephlr** [comment]
It seems like you are using an old version of `rand_core` (0.5.1), which means you are probably also using v0.1 of `getrandom` (i.e. a version that doesn't have the "js" feature).

Does this issue still persist when upgrading rand_core to version v0.6 (or `rand` to v0.8)? Then you should be depending on  `getrandom` v0.2.

If you _must_ use `getrandom` v0.1 (which we would not reccomend), you can enable web support by adding:
```
getrandom = { version = "0.1", features = ["wasm-bindgen"] }
```
as noted in our [v0.1 docs](https://docs.rs/getrandom/0.1.16/getrandom/index.html#support-for-webassembly-and-asmjs)

**Comment by vdods** [comment]
Ah, this was indeed it.  I didn't happen to catch the two different version dependencies in my `cargo tree`.

Thank you!
