### ISSUE TITLE
Use getentropy() libc function on Emscripten

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#275]
[Release 2.0.5: 09/28/2020](https://emscripten.org/docs/introducing_emscripten/release_notes.html) of Emscripten introduced a `getentropy()` call that can be used instead of opening `/dev/urandom`. We should use this as the preferred (or sole) method to get random data, as it avoids needing to open a file and hold onto a file descriptor.

NOTE: this probably requires getting the emscipten CI working with a recent-ish version

**Comment by briansmith** [comment]
> [Release 2.0.5: 09/28/2020](https://emscripten.org/docs/introducing_emscripten/release_notes.html) of Emscripten introduced a `getentropy()` call that can be used instead of opening `/dev/urandom`. We should use this as the preferred (or sole) method to get random data, as it avoids needing to open a file and hold onto a file descriptor.

I do agree that the file descriptor mechanism is worse. However, isn't Emscripten's `getentropy()` reimplementing what the `getrandom` crate does for the browser wasm32 target? Why not just use our own logic instead?

**Comment by josephlr** [comment]
> However, isn't Emscripten's `getentropy()` reimplementing what the `getrandom` crate does for the browser wasm32 target? Why not just use our own logic instead?

IIUC, the point of the Emscripten target is to not use things like `wasm-bindgen`, but instead link to the EMSDK's libc. Then that libc crate can provide all the necessary functionality to emulate an Unix system while running in a wasm/asm.js environment. More practically, wasm-bindgen doesn't support Emscripten targets, so we couldn't do what we do for `wasm32-unknown-unknown` on `wasm32-unknown-emscripten`.
