### ISSUE TITLE
Wrong link in the docs links to rust-bindgen instead of wasm-bindgen

### ISSUE THREAD

**Issue by Kazhuu** [rust-random/getrandom#277]
The [WebAssemmbely](https://docs.rs/getrandom/latest/getrandom/#webassembly-support) docs section seems want to link to [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen), but links to [rust-bindgen](https://github.com/rust-lang/rust-bindgen) instead. 

I assume this is an error right? I also noticed the issue https://github.com/rust-random/getrandom/issues/267, which could be fixed at the same time as this one when the documentation is updated.

**Comment by newpavlov** [comment]
Yes, it's an error. Thank you for reporting it!
