### ISSUE TITLE
target is not supported-Mac M1 (cargo build-bpf )

### ISSUE THREAD

**Issue by johnvsnagendra** [rust-random/getrandom#287]
Bumping up issue #237 

Is there any workaround for running cargo build-bpf in Mac M1?
I am still facing this issue in mac and did not find any solution. Any suggestions will be helpful.
Thanks

**Comment by josephlr** [comment]
As noted in that issue, that target isn't supported. Is there something unclear in the error message or linked documentation?

**Comment by josephlr** [comment]
Closing this, and we can move questions about the docs to #237 

If people think the docs are unclear, open an issue or PR with what you think should be changed.

If there's a way to support the `cargo build-bpf` target, PRs adding support would be welcome.
