### ISSUE TITLE
All test cases use buffers that are multiples of the word size

### ISSUE THREAD

**Issue by briansmith** [rust-random/getrandom#290]
Consider this change to `rdrand_exact()`:

```diff
@@ -91,7 +91,7 @@ unsafe fn rdrand_exact(dest: &mut [u8]) -> Result<(), Error> {
     let tail = chunks.into_remainder();
     let n = tail.len();
     if n > 0 {
-        tail.copy_from_slice(&rdrand()?[..n]);
+        unreachable!()
     }
     Ok(())
 }
```

I would expect at least one test to fail with this modification, but they all pass, because every test buffer is a multiple of the word size. We should have tests for this branch.

**Comment by josephlr** [comment]
Thanks! This is a good catch, we should add (a bunch) of tests with weird-length buffers.
