### ISSUE TITLE
Audit: Ensure there are no assumptions that inputs are reasonably sized

### ISSUE THREAD

**Issue by briansmith** [rust-random/getrandom#292]
When reviewing PR #279 I noticed at least one instance where we assume that a Rust object is no more than `isize::MAX` bytes long. Although that PR was closed, we should still audit that we do not make that assumption elsewhere in the code. See https://github.com/rust-lang/rust/issues/101899#issuecomment-1256855113 and more comments in that issue for evidence that such assumptions aren't generally safe. Arguably the user is doing the wrong thing and triggering UB themselves, but we shouldn't exasperate it.

**Comment by josephlr** [comment]
I agree with this, it seems like a reasonable idea, and it doesn't seem that hard to do.

**Comment by newpavlov** [comment]
It could be worth to ask the WASI guys to clarify the length argument of `random_get`, whether it MUST be smaller than `i32::MAX` or is it interpreted as `u32`.

I don't think we have similar assumptions in other backends, but I agree it's worth to check to be safe.

**Comment by newpavlov** [comment]
It looks like use of `i32` is a quirk of the `wasi` crate, which uses `i32` for all input parameters and return results of WASI "syscalls". In the WASI spec the length parameter is defined as `u32`. See https://github.com/bytecodealliance/wasi/issues/67.

**Comment by briansmith** [comment]
`register_custom_getrandom!` generates a function with the following implementation:
```
        extern "C" fn __getrandom_custom(dest: *mut u8, len: usize) -> u32 {
            let f: fn(&mut [u8]) -> Result<(), $crate::Error> = $path;
            let slice = unsafe { ::core::slice::from_raw_parts_mut(dest, len) };
            match f(slice) {
                Ok(()) => 0,
                Err(e) => e.code().get(),
            }
        }
```
implicit in this implementation is the expectation that `len < isize::MAX` since that is a requirement of `from_raw_parts_mut`: "The total size `len * mem::size_of::<T>()` of the slice must be no larger than `isize::MAX`". Probably `register_custom_getrandom!` should change how it generates the implementation so that it uses chunking, especially since the caller might not be a Rust function passing a pointer to a (validly-sized) Rust object.

**Comment by josephlr** [comment]
> Probably `register_custom_getrandom!` should change how it generates the implementation so that it uses chunking, especially since the caller might not be a Rust function passing a pointer to a (validly-sized) Rust object.

I don't think this is necessary. `__getrandom_custom` can only be called by the [custom `getrandom_inner` implementation](https://github.com/rust-random/getrandom/blob/cfdad53dcefa01e2235b72df7290ae76c7163ac3/src/custom.rs#L93-L102). `__getrandom_custom` is not part of this crate's external API (we do not document it anywhere, and it is prefixed with `__`).

So not having chunking for the `custom` implementation is equivalent to saying that the following is always fine:
```rust
fn foo(buf: &mut [u8]) -> &mut [u8] {
  slice::from_raw_parts_mut(buf.as_mut_ptr(), buf.len())
}
```
which IIUC is always valid in Rust.

**Comment by josephlr** [comment]
The fact that a slice can never exceed does seems to be use [in the standard library](https://github.com/rust-lang/rust/blob/092255976862c1f0121bb4446acd38336a860c4f/library/core/src/slice/mod.rs#L549-L555).

**Comment by briansmith** [comment]
> The fact that a slice can never exceed isize::MAX bytes does seems to be used [in the standard library](https://github.com/rust-lang/rust/blob/092255976862c1f0121bb4446acd38336a860c4f/library/core/src/slice/mod.rs#L549-L555).

The issue isn't about slices, but about whether a general `(*mut u8, usize)` pair. Since it's `#[no_mangle]`, `__getrandom_custom` will be visible globally in the entire executable/library, including from non-Rust code, even if we don't document it's there. I didn't see anything in the documentation that tells people they shouldn't call it directly. And Hyrum's Law says somebody is probably calling it directly even if they shouldn't.

Regarding the extremely unlikely case that `len` is too large, we can actually safely handle it at basically no cost and without chunking:
```rust
// Ensure `len` is a valid slice length.
    let _ = isize::try_from(len).map_err(|_| Error::WHATEVER)?;
```

**Comment by newpavlov** [comment]
>I didn't see anything in the documentation that tells people they shouldn't call it directly.

Starting names with `__` is common to indicate private items, even if technically they are visible. Even `std` relied on this convention when `#[non_exhaustive]` was not implemented yet.

**Comment by josephlr** [comment]
> Regarding the extremely unlikely case that `len` is too large, we can actually safely handle it at basically no cost and without chunking:

I like this approach and would be fine with adding it. It's essentially free and properly alerts the user that _something_ has gone wrong in their program.

**Comment by newpavlov** [comment]
>Regarding the extremely unlikely case that len is too large, we can actually safely handle it at basically no cost and without chunking

It introduces branching, which will be hit every `getrandom` call. The branching can not be optimized by compiler since `__getrandom_custom` is effectively opaque for it. Granted, the branch overhead is minuscule, but it's not zero.

**Comment by briansmith** [comment]
> It introduces branching, which will be hit every `getrandom` call. The branching can not be optimized by compiler since `__getrandom_custom` is effectively opaque for it. Granted, the branch overhead is minuscule, but it's not zero.

In most CPUs the branch will be effectively optimized away since it's never taken. If we look at the other implementations, they (almost?) all have a branch of some kind and it doesn't make a difference.

> @briansmith Assuming `__getrandom_custom` is completely private (i.e. it can not be called directly, only through the public `getrandom` functions), do you agree that in such case chunking or error reporting on `len > isize::MAX` is unnecessary?

In some sense already it isn't really "necessary" since I think we all acknowledge that the bad situation is extremely unlikely. I encountered this when trying to write the `// SAFETY:` comment for the custom.rs use of `unsafe { ... }`. I didn't (don't) want to write a bunch of caveats when I could just add one line to eliminate them.

**Comment by newpavlov** [comment]
I've taken a cursory look over our code base and I think we can close this issue. We can open new issues on case-by-case basis.
