### ISSUE TITLE
Add support for wasm64-unknown-unknown

### ISSUE THREAD

**Issue by briansmith** [rust-random/getrandom#296]
The Rust 1.64.0 release added wasm64-unknown-unknown as a Tier 3 target. https://github.com/rust-lang/rust/blob/stable/RELEASES.md#compiler-11. Since it is Tier 3, it is non-trivial to build/test for this target. However, we should plan on supporting it. I think the key thing will be to stop assuming all the WebAssembly stuff is necessarily 32-bit.

**Comment by josephlr** [comment]
This seems reasonable, I wondering if there's any existing implementations to test against? Do Node or any of the Browser runtimes support `wasm64`?
