### ISSUE TITLE
Windows: buffer uninitialized if longer than 2^32 bytes

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#31]
The [Windows implementation for `getrandom_inner()`](https://github.com/rust-random/getrandom/blob/bcad3fb877e04536b07177d1e1b995a88c428d5d/src/windows.rs#L21) calls [`RtlGenRandom`](https://docs.microsoft.com/en-us/windows/desktop/api/ntsecapi/nf-ntsecapi-rtlgenrandom). However, the length parameter is a `ULONG` (i.e. a `u32`). 

Thus, if a buffer of length `2^32` is passed to `getrandom()` on Windows, the call `dest.len() as ULONG` [truncates the value](https://doc.rust-lang.org/reference/expressions/operator-expr.html#semantics) to 0. This results in the function seeming to succeed, but without writing any data. 

Thanks to @briansmith's [*ring* implementation](https://github.com/briansmith/ring/blob/8237fac8be15a7f0142e8c838a8eaf037a3ad225/src/rand.rs#L172-L179), for pointing this out.

**Comment by dhardy** [comment]
So the ring implementation just truncates large requests to 4 GiB? We use `.chunks_mut` for several backends already, so should just to the same here.

**Comment by newpavlov** [comment]
Good catch! Yes, `chunks_mut(u32::MAX)` looks like a good solution.
