### ISSUE TITLE
Linux: implementation incorrectly returns errors on large buffers

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#32]
If the buffer passed to the Linux [`getrandom(2)`](http://man7.org/linux/man-pages/man2/getrandom.2.html) system call is longer than 256 bytes, the buffer can be partially written. This happens when the system call is interrupted, which becomes more likely the longer the buffer is.

The current implementation returns an error in this case, when it should just try the call again, attempting to fill the remainder of the buffer.

Thanks to @briansmith's [*ring* implementation](https://github.com/briansmith/ring/blob/8237fac8be15a7f0142e8c838a8eaf037a3ad225/src/rand.rs#L194-L199), for pointing this out.

**Comment by dhardy** [comment]
We used to have specific handling for interruptions, but at a higher level (in the Rand lib), so the code this descends from just forwarded the error. But I agree, it makes more sense to retry within `getrandom` now.

**Comment by newpavlov** [comment]
We have discussed it as part of error-handling story, one possible solution is to add `is_retryable` method to the `Error` type and `Error::ITERRUPTED` constant, so users will be able to re-try if needed.

I am not sure if unconditionally retrying on `EINTR` is a correct approach. I am not very knowledgeable on signal handling, but IIRC if signal handler returns the `SA_RESTART` flag syscall gets restarted automatically without returning `EINTR`.

**Comment by josephlr** [comment]
> I am not sure if unconditionally retrying on EINTR is a correct approach. I am not very knowledgeable on signal handling, but IIRC if signal handler returns the SA_RESTART flag syscall gets restarted automatically without returning EINTR.

Not all signal handlers have to do this, and it seems like in `std` Rust just retries blocking operations when it gets `EINTR`, both for [RNG](https://github.com/rust-lang/rust/blob/42503d57907ca13e062ee614b1753ab818c7b016/src/libstd/sys/unix/rand.rs#L48) and [mos syscalls in general](https://github.com/rust-lang/rust/commit/674d24e2e6fad26fc4cedc2fe935ade63198ba7e). As `getrandom()` presents a blocking API, retrying on EINTR seems correct.
