### ISSUE TITLE
Test wasm32-unknown-unknown in Safari on macOS

### ISSUE THREAD

**Issue by briansmith** [rust-random/getrandom#320]
Now CI tests Firefox and Chrome on Linux for wasm32-unknown-unknown. We should run the same tests on Safari and Edge.

**Comment by josephlr** [comment]
Testing safari will be the hardest (unsurprisingly). Currently `safariwebdriver` is broken when used with `wasm-bindgen`: https://github.com/rustwasm/wasm-bindgen/issues/3004

**Comment by josephlr** [comment]
We've got these tests running, so as soon as Safari fixes their bug, our tests will start passing. Closing this as there's nothing else we need to do.
