### ISSUE TITLE
Requesting a release

### ISSUE THREAD

**Issue by chutten** [rust-random/getrandom#349]
Hi! We're hoping to use this to resolve an infrequent and irritating crash in Firefox (see [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1816953)) now that we've updated our stdlib to a fixed version.  Are there any plans for a release in the near term?

**Comment by josephlr** [comment]
Cutting a `v0.2.9` release seems reasonable to me. It seem like the only API change is in #291. However, I'm not sure if free functions are the right API for future-proofing extensions to this crate.

@newpavlov would you be OK:
  - temporiliy reverting #291,
  - Having a bug fix only releae `v0.2.9`
  - Add back #291
  - Have further discussion about the API

**Comment by newpavlov** [comment]
@josephlr 
>However, I'm not sure if free functions are the right API for future-proofing extensions to this crate.

Could you expand on that? Note that we may release `getrandom v0.3` in future without causing too much trouble downstream. Most of the ecosystem does not use `getrandom` directly and instead relies on `rand_core` and it does not expose any types from `getrandom` in its public API.

**Comment by josephlr** [comment]
> Could you expand on that? Note that we may release `getrandom v0.3` in future without causing too much trouble downstream. Most of the ecosystem does not use `getrandom` directly and instead relies on `rand_core` and it does not expose any types from `getrandom` in its public API.
> 
> Right now I do not see the need for reverting `getrandom_uninit` and think that we can do release with it.

See https://github.com/rust-random/getrandom/pull/353 for the basic idea. If we think something like that is _maybe_ worth doing, we can revert #291 and release v0.2.9 while we discuss it.

**Comment by newpavlov** [comment]
I don't think your proposal conflicts with existence of `getrandom_uninit`. You left the `getrandom` function as a safe default which simply wraps the default option, so `getrandom_uninit` can be handled in the same way.

But if you feel more comfortable releasing v0.2.9 without `getrandom_unit` and feel strongly about it... I am fine with its temporary removal, though I personally would prefer to keep it in the new release.

**Comment by josephlr** [comment]
> I don't think your proposal conflicts with existence of `getrandom_uninit`. You left the `getrandom` function as a safe default which simply wraps the default option, so `getrandom_uninit` can be handled in the same way.

That seems fair. I'm good to do a release with `getrandom_uninit`.

Final question, in https://github.com/rust-random/getrandom/pull/293#issuecomment-1286492125 we talked about `fill_uninit` being a better name than `getrandom_uninit`, do we want to change the name to `fill_uninit` now?

**Comment by newpavlov** [comment]
I think `getrandom_uninit` will be a more consistent name for now. In future we may rename it together with `getrandom`.

**Comment by josephlr** [comment]
Sounds good, let's cut a release. I can do it Monday, but I'm OOO until then.

**Comment by josephlr** [comment]
Published: https://crates.io/crates/getrandom/0.2.9
