### ISSUE TITLE
Constant `__getrandom_internal` should have UPPER_SNAKE_CASE name, e.g. `__GETRANDOM_INTERNAL`rust-analyzernon_upper_case_globals

### ISSUE THREAD

**Issue by ethever** [rust-random/getrandom#368]
Constant `__getrandom_internal` should have UPPER_SNAKE_CASE name, e.g. `__GETRANDOM_INTERNAL`rust-analyzer[non_upper_case_globals](https://doc.rust-lang.org/rustc/?search%3Dnon_upper_case_globals)

with `getrandom = { version = "0.2", features = ["custom"] }`

**Comment by josephlr** [comment]
Fair point, ideially we would just call it `_`, but that requires Rust 1.37. Changing the name of `__getrandom_internal` shouldn't break anything. It's name doesn't matter unlike `__getrandom_custom`.

**Comment by ethever** [comment]
Okkk... seems the `#[allow(non_upper_case_globals)]` only works after `Rust 1.59`
