### ISSUE TITLE
Broken link to sys_read_entropy

### ISSUE THREAD

**Issue by WhyNotHugo** [rust-random/getrandom#373]
There's a broken link in the docs:

https://github.com/rust-random/getrandom/blob/8c8ca323f99f65d4f179c66e1ab6b81e92b9a70c/src/lib.rs#L183

I was going to send a PR instead of a patch, but it looks like this documentation is gone and not available online elsewhere.

Looking around I get an impression that it's been deprecated entirely? E.g.: https://github.com/hermitcore/, https://github.com/hermit-os/libhermit#deprecation-notice

**Comment by josephlr** [comment]
Seems like the right doc is https://docs.rs/hermit-abi/0.3.3/hermit_abi/fn.read_entropy.html

**Comment by WhyNotHugo** [comment]
Indeed it is, thanks.

**Comment by newpavlov** [comment]
We do not rely on the `hermit-abi` crate, so I think it would be better to link the [source code](https://github.com/hermit-os/kernel/blob/315f58ff5efc81d9bf0618af85a59963ff55f8b1/src/syscalls/entropy.rs#L47-L55) directly.

**Comment by josephlr** [comment]
Good point seems like https://github.com/hermit-os/kernel/blob/315f58ff5efc81d9bf0618af85a59963ff55f8b1/src/syscalls/entropy.rs#L47-L55 should worj
