### ISSUE TITLE
Don't fall back to file I/O on Linux when Rust only supports kernels guaranteed to have it

### ISSUE THREAD

**Issue by briansmith** [rust-random/getrandom#376]
According to https://doc.rust-lang.org/beta/rustc/platform-support.html, there are only a handful of target architectures where Rust supports kernels that are so old that they would not have the `getrandom` syscall. Notably `riscv64gc` and `aarch64` are guaranteed to have `getrandom` according to the Rust kernel support policy. For those architectures we should not have enable the fallback logic at all. I suggest in particular that we have an allowlist of target architectures where we allow the fallback, which would be `i686`, `x86_64`, `arm`, `armv7`, `powerpc`, `powerpc64`, `powerpc64le`. `s390x`, `i586`, according to the Rust documents.

**Comment by josephlr** [comment]
I like this idea, it also serves as a bit of a test run for removing such file-based support once rust increases its supported kernel version.

**Comment by newpavlov** [comment]
Sounds good to me!

**Comment by newpavlov** [comment]
What about Android targets?

In this [issue](https://github.com/briansmith/ring/issues/852) @josephlr wrote
>We need to have a /dev/urandom fallback and will need it at least until the 3.16 kernel ends LTS support in mid 2020.

So we probably can disable file fallback for Android targets as per our [platform support policy](https://github.com/rust-random/getrandom?tab=readme-ov-file#platform-support)?

**Comment by briansmith** [comment]
> So we probably can disable file fallback for Android targets as per our [platform support policy](https://github.com/rust-random/getrandom?tab=readme-ov-file#platform-support)?

I have been assuming `getrandom`'s platform support is that of its MSRV, not the latest stable Rust version. We we need to go back and look at what the kernel support policy of Rust 1.36 was.

**Comment by workingjubilee** [comment]
That documentation was introduced in 1.47.0: https://doc.rust-lang.org/1.47.0/rustc/platform-support.html
