### ISSUE TITLE
Potential undefined behavior in hermit implementation.

### ISSUE THREAD

**Issue by briansmith** [rust-random/getrandom#377]
https://github.com/rust-random/getrandom/blob/35808a4b2747aa2c46e159239fba29454eb28663/src/hermit.rs#L4-L7

https://github.com/rust-random/getrandom/blob/35808a4b2747aa2c46e159239fba29454eb28663/src/hermit.rs#L9-L16

* If `res == -sizie::MIN` then `(-res)` will overflow. To fix, use `checked_neg()`.
* if `res < (i32::MIN as isize)` then `(-res) as u32` is a truncating, i.e. lossy conversion. To fix: avoid using `as` for integer conversions and instead use `TryInto` for this conversion.
* if `(-res) % 0x1_0000_0000 == 0` then `(-res) as u32` is zero and then `NonZeroU32::new_unchecked((-res) as u32)` is undefined behavior. To fix, use the safe `NonZerou32::new()` instead.

Maybe somewhere hermit guarantees errors codes will never be this large but better to avoid the issue completely.

Something like:
```
     let code = res.checked_neg().map(u32::try_from).map(NonZeroU32::new).unwrap_or(something);
```
There would be no undefined behavior in the new version.

**Comment by newpavlov** [comment]
Negation of `isize::MIN` by itself does not cause UB, according to the reference in such cases negation simply returns `MIN`. The problem, as you noted, is with truncated conversion, which may result in 0. For example, a similar issue may be caused on 64 bit targets by `-(1isize << 33)`.

As can be seen by the linked source code, Hermit uses `i32` for error codes and `i32::MIN` will not cause UB, though the resulting error code will be in the custom error range. Also, according to the [syscall docs](https://github.com/hermit-os/kernel/blob/0564975d1deed98ab7b3c1884d60925c596e170a/src/syscalls/entropy.rs#L51C8-L51C15), `sys_read_entropy` can only return `-EINVAL` and `-ENOSYS`.

So I think the current code is fine, but I am not against improving robustness of the code.

**Comment by josephlr** [comment]
I think if we want things to be more robust, we should pursue just using the `hermit-abi` crate. This seems to be what [`libstd` does for hermit targets](https://github.com/rust-lang/rust/blob/4af886f8ab94543caad689ee6bf6a93fa8bd4a98/library/std/Cargo.toml#L45C1-L46C83), so it would also make things more consistent.
