### ISSUE TITLE
embedded source compatibility

### ISSUE THREAD

**Issue by dhardy** [rust-random/getrandom#4]
This crate requires `std::io` code on many platforms to read from special devices, therefore will normally require `std`. Ideally we should provide a smooth route to `no_std` compatibility however, possibly by allowing users to define `extern` functions. (We've discussed using "lang items" but these are restricted to Rust's core libraries; we may or may not integrate this code into `std` in the future and use that option, but ideally should have a `no_std` option now.)

**Comment by dhardy** [comment]
One solution here would be a special feature enabling an alternative mode:
```rust
#[cfg(feature = "getrandom_custom")]
extern "C" {
    fn getrandom_custom(dest: *mut u8, len: usize) -> u32;
}

pub fn getrandom(dest: &mut [u8]) -> Result<(), Error> {
    #[cfg(feature = "getrandom_custom")] {
        use core::num::NonZeroU32;
        let ret = unsafe { getrandom_custom(dest.as_mut_ptr(), dest.len()) };
        return if let Some(err) = NonZeroU32::new(ret) {
            Err(Error::from(err))
        } else {
            Ok(())
        };
    }
    getrandom_inner(dest)
}
```
This would allow *any* single crate in the build to replace the entropy source, which has both advantages (easier testing with dummy entropy, easy of usage of other randomness source libs) and disadvantages (relatively easy to accidentally or possibly even maliciously mess this up; no single place to check whether the alternative is enabled).

---

Another solution (which doesn't need any support here) would be to make a replacement crate with the same API (copy error types, provide `fn getrandom`), then use a patch section in the top `Cargo.toml` to replace this.
```toml
[patch.crates-io]
getrandom = { path = "my/replacement/getrandom" }
```

**Comment by dhardy** [comment]
There is another issue with `no_std` support: the error type should implement `std::error::Error` iff using `std`. Currently the lib does so on all platforms except SGX, i.e. this is automatic and requires `std` on all platforms which *should* support `std`. IIRC we did once have a reason to disable support on Mac OS.

In contrast, `rand_core` makes std-support a crate feature, and causes confusing errors if you get this wrong in the build.

**Comment by dhardy** [comment]
Note: there is a long discussion on this topic in rand#579 with several sub-topics:

- [a hook to set an entropy source](https://github.com/rust-random/rand/pull/579#issuecomment-410464293)
- [synchronisation/shared memory](https://github.com/rust-random/rand/pull/579#issuecomment-417260440)
- [managing an entropy pool](https://github.com/rust-random/rand/pull/579#issuecomment-424288367)
- [use of lang items](https://github.com/rust-random/rand/pull/579#issuecomment-424443465)

At any rate, development appears to be stalled due to lack of demand.

**Comment by tarcieri** [comment]
@dhardy I opened an issue on the embedded WG to call attention to the issue of `no_std` support: https://github.com/rust-embedded/wg/issues/353

**Comment by dhardy** [comment]
Some of the ideas aired above may still be relevant in the future, e.g. use of an entropy pool (via another crate). This issue is too broad I guess, ranging from `std` dependencies to how to get entropy on embedded platforms. Perhaps I should rename it to focus on that?

**Comment by mati865** [comment]
https://github.com/rust-random/getrandom/pull/58 haven't changed that much regarding `no_std`/embedded because it's still using https://github.com/rust-random/getrandom/blob/00c3cff1012c638d4b9eab81faf14aab50d49fea/src/error_impls.rs#L8

**Comment by newpavlov** [comment]
@mati865 
This module is [feature gated](https://github.com/rust-random/getrandom/blob/master/src/lib.rs#L180) behind the `std` feature.

**Comment by mati865** [comment]
@newpavlov I totally missed that gate and couldn't find default features field for this crate. I haven't thought about other rand crates enabling it.
Thank you for the explanation and sorry for the noise.

**Comment by josephlr** [comment]
Do we think that Custom RNGs (#109) and the `cpu` feature (#133) are sufficient to close this issue?

**Comment by tarcieri** [comment]
@josephlr I think both of those PRs are irrelevant to the embedded use case, as none of them cover embedded targets.

Per the discussion on https://github.com/rust-embedded/wg/issues/353 I’m wondering of the getrandom API is fundamentally incompatible with `embedded-hal` style TRNG peripherals, since getrandom generates randomness as a side effect, and accessing a TRNG will typically involve passing in an owned peripheral device.

I think the existing `RngCore` trait probably provides the most embedded-friendly API.

**Comment by josephlr** [comment]
#109 (in addition to dealing with WASM targets) also adds a generic way for an external crate to register a custom getrandom implementation. This concept of an externally defined hook was specifically intended to work with embedded targets.

For example, if there was some external device that you want to get randomness from, you would write a custom crate which would depend on `getrandom` like:
```toml
name = "mydevice-getrandom"
[dependencies]
getrandom = { version = "0.2", features = ["custom"] }
```

And your code would then specify a function to be called. A sample `lib.rs` would look like:
```rust
use spin::Mutex;
use getrandom::{register_custom_getrandom, Error};

struct Device{ /* device specific state */ }

impl Device {
  fn new() -> Result<Self, Error> {
    /* Initialize and Create the device */
  }
  fn read(&mut self, buf: &mut [u8]) -> Result<(), Error> {
    /* Read randomness from the device */
  }
}

// Global instance of device
static DEVICE: Mutex<Option<Device>> = Mutex::new(None);

fn my_getrandom(buf: &mut[u8]) -> Result<(), Error> {
  let mut guard = DEVICE.lock();
  let dev: &mut Device = guard.get_or_insert(Device::new()?);
  dev.read(buf)
}

register_custom_getrandom!(my_getrandom);
```
The above code uses the `no_std`-compatible [`spin::Mutex`](https://docs.rs/spin/0.5.2/spin/struct.Mutex.html), but you could also use [`lock_api::Mutex`](https://docs.rs/lock_api/0.3.3/lock_api/struct.Mutex.html) if you wanted to [avoid spin locks](https://matklad.github.io/2020/01/02/spinlocks-considered-harmful.html) and use platform specific synchronization primitives.

@tarcieri, Is there a reason that wouldn't work for your use case?

**Comment by josephlr** [comment]
While the [embedded-hal](https://docs.rs/embedded-hal/0.2.3/embedded_hal/) crate specifically seems to encourage Global Singletons (per their example code), I realize that this does not map onto all workflows.

Alternatively, if you had some device-specific `mydevice` crate which exported an api like:
```rust
struct Device{/* private */}

impl Device {
  fn get_mut() -> Result<&mut Self, Error>;
  fn read(&mut self, buf: &mut [u8]) -> Result<(), Error>;
}
```

You could implement a `mydevice-getrandom` crate like:
```rust
use mydevice::Device;
use getrandom::{register_custom_getrandom, Error};

fn my_getrandom(buf: &mut[u8]) -> Result<(), Error> {
  Device::get_mut()?.read(buf)
}

register_custom_getrandom!(my_getrandom);
```

**Comment by tarcieri** [comment]
Well first, the `spin` crate is unmaintained... that aside...

I suppose this accomplishes the goal of having something that potentially works for embedded, however I think it’s complex solution as opposed to passing a `&mut MyTrng` where `MyTrng: RngCore`.

I’d probably still choose to use `RngCore` over `getrandom` for anything intended for embedded use.

**Comment by josephlr** [comment]
> I’d probably still choose to use `RngCore` over `getrandom` for anything intended for embedded use.

I'd agree that's the best bet if you're using something directly. The main reason for the custom impl is to handle cases where `getrandom` is a transitive dependency, because in that case you might not be able to pass around state.

**Comment by dhardy** [comment]
Appologies for the late reply. @josephlr's [example above](https://github.com/rust-random/getrandom/issues/4#issuecomment-589449803) can certainly be adapted to keep the global singleton but perform initialisation via a user-called function — it just means that `getrandom` must block or fail if called before this happens.

However, granted, this is a lot more complexity than strictly required. `getrandom` was intended for initialising `ThreadRng` and similar constructs which *just work* — but attempting to make this compatible with non-std targets may simply be misguided (since the latter also requires thread-local memory or global memory with a lock, and the whole construct carries a lot more complexity than is desirable on embedded).

Should we then close this issue as not-worth-delivering?

**Comment by tarcieri** [comment]
#109 seems good enough to address the immediate issue

**Comment by dhardy** [comment]
Guess I'll close this then.
