### ISSUE TITLE
Remove file-based RNG fallback on DragonflyBSD

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#402]
In https://github.com/rust-lang/rust/pull/121942 (also see https://github.com/rust-lang/rust/pull/122356), `libstd` moved to just unconditionally calling `libc::getrandom` on Dragonfly BSD. This breaks Dragonfly BSD releases before 5.7, but this was judged to be acceptable (based on what targets Rust wants to support).

@newpavlov would it make sense for us to do the same thing?

Blocked by: https://github.com/rust-lang/libc/pull/3618

**Comment by newpavlov** [comment]
Yes, I think we can follow `std` here as per our platform support policy.

**Comment by newpavlov** [comment]
This is currently blocked on https://github.com/rust-lang/libc/pull/3618
