### ISSUE TITLE
Document and Test that `getrandom()` never panics.

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#435]
Spun off of the review of #434 

We should have a way to verify in the CI that our implementation (at least on easy-to-test architectures) does not panic. This could be done via the [`no-panic` crate](https://crates.io/crates/no-panic) as a dev-dependancy.

**Comment by newpavlov** [comment]
A slightly easier approach could be to check whether generated `rlib` file contains any strings with `panic`. It will not catch any potential panics in uninlined functions from our dependencies (I think `no-panic` is similar in this regard) and may break if in future we will add an item with "panic" in it (e.g. an error description). This approach also may be friendlier to cross-compilation.

**Comment by josephlr** [comment]
> A slightly easier approach could be to check whether generated `rlib` file contains any strings with `panic`.

One thing to look out for is that our current implementation [will emit references to `panic_in_cleanup`](https://rust.godbolt.org/z/Ydcdz4aGo) due to our use of `DropGuard`. This is because the compiler can't statically determine that `libc::close` and `libc::pthread_mutex_unlock` will not panic. [Replacing them with Rust stubs](https://rust.godbolt.org/z/xPea169Kd) removes the `panic_in_cleanup` references.

In general `panic_in_cleanup` is fine, as it will never _create_ a panic, it just aborts the process.

**Comment by briansmith** [comment]
Eventually it would be good to eliminate all uses of the panic infrastructure (and runtime library in general), but use_file and the fallback logic is the least urgent, IMO.
