### ISSUE TITLE
Shared file descriptor is closed prematurely

### ISSUE THREAD

**Issue by josephlr** [rust-random/getrandom#44]
[Here](https://github.com/rust-random/getrandom/blob/master/src/use_file.rs#L38), we create a `File` from a raw fd. However, as this object is created on the stack, at the endo the function, the file will be dropped, and thus closed.

This means that on systems using a shared FD, the second call to `getrandom` will fail. This can be fixed by just storing a `File` instead of a `RawFd` in static memory.

**Comment by newpavlov** [comment]
Yes, code should use `mem::forget(f)`, I was [doing it](https://github.com/rust-random/getrandom/pull/14/files#diff-2c86afbaa5a58b22593d4d348ab69620R74), but missed it during review...

You can't store `File`, as `Read` impl requires an exclusive access. You could use `try_clone`, but I think it will be slightly less efficient.
