### ISSUE TITLE
Force use of `rdrand` feature instead of `linux_android` implementation

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [rust-random/getrandom#491]
I'm trying to use `rdrand` on `x86_64-unknown-linux-gnu` but `linux_android` implementation is used instead. This happens because `cfg-if` selects `linux_android` first.

**Comment by newpavlov** [comment]
We intentionally do not allow users to overwrite the "default" backends. Why do you want to use RDRAND instead of the `getrandom` syscall? If you _really_ need it, then your only option right now is to use dependency patching.

**Comment by josephlr** [comment]
Also if you wish to always use rdrand, and never use the OS source of entropy (the primary purpose of this crate), you can just use the [`rdrand`](https://crates.io/crates/rdrand) crate.
