### ISSUE TITLE
Consider updating to `wasi v0.13.1+wasi-0.2.0`

### ISSUE THREAD

**Issue by LikeLakers2** [rust-random/getrandom#492]
Hi! I noticed that `getrandom` appears to be using `wasi v0.11.0+wasi-snapshot-preview1`. The latest version of `wasi` is `wasi v0.13.1+wasi-0.2.0`.

I would normally recommend updating `getrandom` to use `wasi v0.13` (newer versions are almost always better). However, I took a quick look at [`wasi`'s repository](https://github.com/bytecodealliance/wasi-rs), specifically their readme, and found that `wasi` itself recommends staying on `v0.11` [in certain circumstances](https://github.com/bytecodealliance/wasi-rs/blob/94e50002c0d3691f54ad370eb2d10ddad4c2777b/README.md#wasip2-vs-wasip1).

Still, I'm hesitant to simply assume that the `getrandom` developers know of any of this - and in any case, I didn't see issues or PRs with information on why `getrandom` isn't using a newer version. So, I wanted to make this issue. If nothing else, it'll be an opportunity to explain why `getrandom` isn't using a newer version.

Thank you in advance.

**Comment by newpavlov** [comment]
IIUC the `wasm32-wasi` target uses the preview1 API, so we should keep using `wasi v0.11` on it and `wasip1` targets. Meanwhile,  `wasi v0.13` should be used for `wasip2` targets.

But I am not sure what value `target_os` has on `wasm32-wasi`, `wasm32-wasip1`, and `wasm32-wasip2`. Is it `wasi`, `wasip1`, and `wasip2`? Or `wasi` for all of them? If it's the latter, I think we have a problem...

**Comment by yoshuawuyts** [comment]
Hey all; I was asked to jump in here and answer this question. We thought WASI 0.2 would land as tier-2 stable in Rust 1.81 (September), but it will be landing in Rust 1.82 instead (November). The right way to target the different WASI flavors is as follows:

```rust
 // target WASI 0.1
 #[cfg(all(target_os = "wasi", target_env = "p1"))]
 mod wasip1 {
     // items go here
 }

 // target WASI 0.2
 #[cfg(all(target_os = "wasi", target_env = "p2"))]
 mod wasip2 {
     // items go here
 }
 ```
 
 You can try this out today with the beta channel. I hope this helps!
