### ISSUE TITLE
Use vDSO on Linux 6.11

### ISSUE THREAD

**Issue by ericlagergren** [rust-random/getrandom#503]
See https://github.com/golang/go/issues/69577

**Comment by briansmith** [comment]
I think this would be good to have opt-in for a while, while the DSO feature is being tested in the real world.

**Comment by newpavlov** [comment]
This may be interesting in the context of #424, but otherwise I think we should just use `libc::getrandom` (maybe through `dlopen` in the backend with `/dev/urandom` fallback) and let it decide how the syscall is handled.

**Comment by newpavlov** [comment]
Closing in favor of #508 and https://github.com/bytecodealliance/rustix/issues/1185.
