### ISSUE TITLE
Add More Documentation

### ISSUE THREAD

**Issue by 0xSilene** [rust-random/getrandom#72]
There isn't a lot of documentation on how to actually use the crate. I used the example from the README.md page, but its throwing errors because its returning a type of [u8;32] instead of the enum Result. I've never used Result so forgive me for not knowing much about it, but I can't seem to get it to work correctly.

I really want to use this crate, as its minimal and its exactly what I need for another crypto project I am working on.

Could you add a full example on how you would generate random bytes as the one in the readme does not work (tested on Mac OS and Windows). Do I have to import std::result::Result as I tried that with no success? I tried messing around with the code and can not get it to work at all.

I then tried compiling with nightly and same thing.

It expects the enum std::result::Result to return, not the array of bytes. Maybe I am just doing something wrong, but it would really help if there was a full example file.

**Comment by newpavlov** [comment]
Oh, there is a small mistake in the readme, the last line should be `Ok(buf)`, not `buf`. I will fix it right away. If you don't mind panicking on potential errors, you can write code like this:
```rust
fn get_random_buf() -> [u8; 32] {
    let mut buf = [0u8; 32];
    getrandom::getrandom(&mut buf).unwrap();
    buf
}
```

But I would **strongly** recommend to learn more about Rust first, as `Result`-based error handling is a really basic Rust concept, otherwise you will not get far. Here is the TRPL chapter about it: https://doc.rust-lang.org/1.30.0/book/2018-edition/ch09-00-error-handling.html

**Comment by 0xSilene** [comment]
Thanks for the link! Yeah I have been trying to learn Rust for the past few weeks. I like it a lot but still have much to learn and have only attempted small projects with it. I love the amount of documentation they have for it. I'm a junior dev, still in school in my off-time trying to learn rust, with very limited C/C++ experience so theres a learning curve I have to get over with more experience.

I am trying to learn as much as I can now about writing good code, and rust so far has helped at filling that need. I hope over time it becomes second-nature to me but I guess that comes with experience.

Thank you, closing issue :)

**Comment by newpavlov** [comment]
After you've read the book, feel free ask questions on [users forum](https://users.rust-lang.org) or [reddit](https://www.reddit.com/r/rust/)!
