### ISSUE TITLE
Broke backwards compatibility without bumping major version

### ISSUE THREAD

**Issue by elichai** [rust-random/getrandom#75]
Hi,
Version `0.1.7` broke backwards compatibility with older rust compilers (like the one shipped with OS and ones that can be safely bootstrapped)
without bumping the major version.

This broke a bunch of stuff in https://github.com/rust-bitcoin/rust-bitcoin
Our users want very specific use cases that require older rust compilers.

I understand if you want to use newer rust code and you don't want to support older versions(this changes broke everything earlier than 1.32) I just ask if 0.1.7 can be yanked and bumped to 0.2 because this is a big break (before 0.1.7 this crate supported compiler versions as early as 1.16)

Would appreciate a response. Thanks!

**Comment by josephlr** [comment]
The `README` has made it clear for awhile that `getrandom` is only supported for Rust 1.32 and later, so the changes in 0.1.7 are not a breaking change. However, if we do increase the minimum supported Rust version (or make any other breaking change), we would release those changes as a 0.2.0.

If you absolutely must use an older version, Cargo supports pinning an exact version.

**Comment by newpavlov** [comment]
I think we can close this issue. Note that `getrandom` working on pre-1.32 is a pure coincidence and even v0.1.6 may not work on other targets.
