### ISSUE TITLE
Redox support

### ISSUE THREAD

**Issue by dhardy** [rust-random/getrandom#79]
https://github.com/rust-random/getrandom/blob/199b11576eea7aab93a0162e36571b8b607f0000/.travis.yml#L105

Since https://github.com/rust-lang/rust/issues/60139 is still open, we probably don't want to do anything about this yet. In this case however we also need to disable rand tests ([see this failure](https://travis-ci.org/rust-random/rand/jobs/567814932)).

**Comment by josephlr** [comment]
So it looks like https://github.com/rust-lang/libc/pull/1450 is what we need to get redox building again, we shouldn't need the changes to the Rust compiler itself. We just need to wait on upstream `libc` to merge it and push another release.

**Comment by mati865** [comment]
Libc CI broke because of migration to Azure Pipelines.

**Comment by newpavlov** [comment]
I have tried to re-enable Redox CI test, but I got the following error:
>component 'rust-std' for target 'x86_64-unknown-redox' is unavailable for download for channel 'nightly'

So IIUC we have to wait for rust-lang/rust#63160.

**Comment by josephlr** [comment]
We could use the `xbuild` style commands for Redox. That’s what we do for targets without rust-std
