### ISSUE TITLE
use with wasm-bindgen triggers CSP error

### ISSUE THREAD

**Issue by evq** [rust-random/getrandom#91]
Due to `let this = Function::new("return this").call(&JsValue::undefined());` I'm currently seeing an error using a sensible CSP:

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-eval'".
```

`js_sys` uses a more involved method to fetch the global object that eventually falls back to the unsafe version. 
https://rustwasm.github.io/wasm-bindgen/api/src/js_sys/lib.rs.html#4450-4523

Can either `js_sys` be added as a dependency or this logic (or a subset) be reproduced here?

**Comment by josephlr** [comment]
Good find @evq I’m working on a patch to fix this for the bindgen target. I think we should be using js_sys at the very least.

**Comment by evq** [comment]
@josephlr Per https://github.com/flexdinesh/browser-or-node/blob/master/src/index.js and https://mathiasbynens.be/notes/globalthis I wonder if some simplified logic may work for this use case? Essentially we check for `self.document` or `self.constructor.name === 'DedicatedWorkerGlobalScope'`, if either is defined we're in a browser and can use `self.crypto`. Otherwise we assume we're in node.
