### ISSUE TITLE
trait impl disappeared without bumping major version

### ISSUE THREAD

**Issue by awortman-fastly** [rust-random/getrandom#94]
Sorry to be the bearer of versioning news, `0.1.10` contains a backwards-incompatible change with respect to `0.1.8` and so on - the feature flags around [`error_impls`](https://github.com/rust-random/getrandom/commit/b69f83221041414b30adbbcef13e3934da2c04f7#diff-b4aea3e418ccdb71239b96952d9cddb6L155-L170) changed, and had been accidentally(?) including `error_impls` for specific OSes regardless of `std` being selected or not.

The change around feature flags makes sense, but without bumping major versions, version `0.1.10` can cause breakages: see the end of the log [here](https://travis-ci.org/fastly/lucet/builds/573939344). The missing impl is because `minisign` depends on `getrandom = "0.1.3"`, where `0.1.10` should be a backwards compatible update, but is not due to the missing trait. We can work around that by specifying `std`, but I wanted to make sure y'all knew about this.

**Comment by newpavlov** [comment]
We could make `std` feature enabled by default. Strictly speaking it also can be viewed as a breaking change for `no_std` targets (especially considering that `rand_core` does not use `default-features = "false"` for `getranom` right now), but since no one has complained about about `compile_error!` on them, I guess it can be considered a lesser evil in this unpleasant situation.

**Comment by josephlr** [comment]
@newpavlov I agree, we should enable the `std` feature by default to fix this issue and have `rand_core` pass `default-features = false` so that `rand_core` keeps working on `no_std` targets (really, we should do that regardless).

We should prioritize not breaking `std` users first and foremost.

**Comment by dhardy** [comment]
I think the solution here is to yank 0.1.10 and prepare 0.2.0?

**Comment by josephlr** [comment]
> I think the solution here is to yank 0.1.10 and prepare 0.2.0?

@dhardy I agree. My idea is as follows:
  - Merge #96 to fix this issue
  - Release 0.1.11 and yank 0.1.10
  - Make backwards incompatible changes, like:
    - Removing the std trait impls for all targets
    - Changes to address #4 and #84 
 - Release 0.2.0 (and update `rand` to use it).
